import productImg1 from "../assets/images/product-img-3.png";
import productImg2 from "../assets/images/product-img-1.png";
import productImg3 from "../assets/images/product-img-2.png";

export const productsData = [
  {
    id: 1,
    name: "Seedra Cilantro Seeds for Planting Indoor and Outdoor 1",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg1,
    inStock: true,
  },
  {
    id: 2,
    name: "SEEDRA Corn - Bodacious Hybrid Seeds for Indoor and Outdoor Planting 2",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg2,
    inStock: true,
    highlighted: true,
  },
  {
    id: 3,
    name: "SEEDRA Spinach Seeds for Indoor and Outdoor Planting 3",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg3,
    inStock: true,
    selected: true,
  },
  {
    id: 4,
    name: "Seedra Cilantro Seeds for Planting Indoor and Outdoor 4",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg1,
    inStock: true,
  },
  {
    id: 5,
    name: "SEEDRA Corn - Bodacious Hybrid Seeds for Indoor and Outdoor Planting 5",
    price: 12.56,
    originalPrice: 15.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg2,
    inStock: true,
    onSale: true,
  },
  {
    id: 6,
    name: "SEEDRA Spinach Seeds for Indoor and Outdoor Planting 6",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg3,
    inStock: true,
  },
  {
    id: 7,
    name: "Seedra Cilantro Seeds for Planting Indoor and Outdoor 7",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg1,
    inStock: true,
  },
  {
    id: 8,
    name: "SEEDRA Corn - Bodacious Hybrid Seeds for Indoor and Outdoor Planting 8",
    price: 12.56,
    originalPrice: 15.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg2,
    inStock: true,
    onSale: true,
  },
  {
    id: 9,
    name: "SEEDRA Spinach Seeds for Indoor and Outdoor Planting 9",
    price: 12.56,
    currency: "USD",
    rating: 4.5,
    reviewCount: 123,
    image: productImg3,
    inStock: true,
    selected: true,
  },
];
